# Generated by Django 3.2 on 2022-02-14 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import job_applications.utils
import job_applications.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=60, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('hiring_contact', models.CharField(default='default', max_length=60)),
                ('hiring_contact_email', models.EmailField(max_length=254)),
                ('is_open', models.BooleanField(default=True)),
                ('metadata', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_applications.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('stage', models.IntegerField(choices=[(1, 'Pending'), (2, 'Reviewing'), (3, 'Shortlisted'), (4, 'Interviewing'), (5, 'Advanced Interviewing'), (6, 'Rejected'), (7, 'Offered'), (8, 'Hired')])),
                ('resume', models.FileField(help_text='Please upload only PDF or docx files', upload_to=job_applications.utils.upload_to_file, validators=[job_applications.validators.validate_file])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_applications.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
